<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en"><!-- InstanceBegin template="/Templates/cn-content-page.dwt" codeOutsideHTMLIsLocked="false" -->

<head>
<meta http-equiv="Content-Language" content="en-CA">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<!-- InstanceBeginEditable name="doctitle" -->
<title></title>
<!-- InstanceEndEditable -->

<!-- InstanceBeginEditable name="metaInformation" -->
<meta name="keywords" content="">
<meta name="description" content="">
<!-- InstanceEndEditable -->

<meta name="author" content="">
<meta name="copyright" content="&copy; University of Ottawa">

<?php include("http://web5.uottawa.ca/assets-templates/inc/head.html"); ?>

<!-- theme -->
<link type="text/css" rel="stylesheet" media="screen" href="http://web5.uottawa.ca/assets-templates/themes/08/main.css">
<!-- site-specific style sheet -->
<link type="text/css" rel="stylesheet" media="screen" href="/assets/css/section-header-cn.css">
<link type="text/css" rel="stylesheet" media="screen" href="/assets/css/main.css">

<!-- include page tools -->
<script type="text/javascript" src="http://web5.uottawa.ca/assets-templates/js/print.js"></script>
<script type="text/javascript" src="http://web5.uottawa.ca/assets-templates/js/send-to-friend.js"></script>

<!-- InstanceBeginEditable name="head" -->
<!-- page variables -->
<script type="text/javascript">
<!--
var expandNavSection = "section";
-->
</script><!-- /page variables -->
<!-- InstanceEndEditable -->
</head>

<body class="en">

<div id="main-container" class="content-page">
<!-- InstanceBeginEditable name="pageLinks" -->
	<ul id="page-links">
		<li><a id="skip-to-content" href="#main-content">Skip to content</a></li>
		<li><a id="skip-to-localnav" href="#local-nav">Skip to links</a></li>
		<li><a id="ch-lang-url" href="http://www.juriglobe.uottawa.ca/index.php" rel="alternate" lang="fr" hreflang="fr">Français</a></li>
		<li><a id="section-home" href="http://www.juriglobe.uottawa.ca/eng/index.php">Return to the home page</a></li>
	</ul>
<!-- InstanceEndEditable -->
	<!-- /#page-links -->

<?php include("http://web5.uottawa.ca/assets-templates/inc/banner-en.html"); ?>

<div id="section-container">

<!-- InstanceBeginEditable name="sectionHeader" -->
<?php virtual("/assets/inc/section-header-cn.html"); ?>
<!-- InstanceEndEditable -->

<div id="page-tools">
<div id="quickpicks">
<ul>
	<?php virtual("/assets/inc/quickpicks-en.html"); ?>
	<?php include("http://web5.uottawa.ca/assets-templates/inc/quickpicks-en.html"); ?>
</ul>
</div><!-- /#quickpicks -->
</div>
<!-- /#page-tools -->

<div id="section-details">
	<!-- InstanceBeginEditable name="Navigation" -->
	<?php virtual("/assets/inc/nav-cn.html"); ?>
	
	<!-- InstanceEndEditable -->
</div>

<div id="main-content">
<?php 
echo "<h4 align=right>";
echo "<a href=", str_replace("/chi/","/eng/",$_SERVER["PHP_SELF"]),">English</a> " ;
echo "<a href=", str_replace("/chi/","/fra/",$_SERVER["PHP_SELF"]),">Français</a> " ;
echo "<a href=", str_replace("/chi/","/esp/",$_SERVER["PHP_SELF"]),">Español</a> " ;
echo "<a href=", str_replace("/chi/","/rus/",$_SERVER["PHP_SELF"]),">Русский</a> " ;
echo "<a href=", str_replace("/chi/","/ara/",$_SERVER["PHP_SELF"]),">عربي</a> " ;
echo "</h4><hr>";
?>
	<!-- InstanceBeginEditable name="mainContent" -->
	<h2>政治实体字母顺序索引 - 按人口与对应法律体系</h2>
	<table cellspacing="3" cellpadding="3">
      <tr>
        <td width="40%"><div align="center"><strong>政治实体</strong></div></td>
        <td width="20%"><div align="center"><strong>人口 （百万）</strong></div></td>
        <td width="20%"><div align="center"><strong> 法律体系</strong></div></td>
        <td width="20%"><div align="center"><strong>混合体系构成</strong></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>亚速尔群岛（葡属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿富汗</td>
        <td>(1) 31.9</td>
        <td>穆斯林法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>南非</td>
        <td>47.4</td>
        <td>混合法 </td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>阿尔巴尼亚</td>
        <td>3.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿尔及利亚</td>
        <td>33.3</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>德国 </td>
        <td>82.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>安道尔</td>
        <td>0.1</td>
        <td>习惯法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>安哥拉</td>
        <td>16.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>安圭拉岛（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>安提瓜和巴布达</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>安的列斯群岛（荷属）</td>
        <td>0.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>沙特阿拉伯</td>
        <td>23.7</td>
        <td>穆斯林法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿根廷</td>
        <td>39.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>亚美尼亚 </td>
        <td>3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿鲁巴（荷属）</td>
        <td>0.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>澳大利亚</td>
        <td>20.5</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>奥地利</td>
        <td>8.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿塞拜疆</td>
        <td>8.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>巴哈马群岛</td>
        <td>0.3</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>巴林 </td>
        <td>0.7</td>
        <td>混合法</td>
        <td>穆斯林法/民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>孟加拉国</td>
        <td>144.3</td>
        <td>混合法</td>
        <td>穆斯林法/普通法</td>
      </tr>
      <tr>
        <td>巴巴多斯</td>
        <td>0.3</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>白俄罗斯</td>
        <td>9.7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>比利时</td>
        <td>10.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>伯利兹</td>
        <td>0.3</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>贝宁</td>
        <td>8.7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>百慕大群岛（英属）</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>不丹</td>
        <td>0.6</td>
        <td>混合法</td>
        <td>习惯法/普通法</td>
      </tr>
      <tr>
        <td>玻利维亚</td>
        <td>9.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>波斯尼亚和黑塞哥维那</td>
        <td>3.9</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>博茨瓦纳</td>
        <td>1.8</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>巴西</td>
        <td>188.7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>文莱</td>
        <td>0.4</td>
        <td>混合法</td>
        <td>穆斯林法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>保加利亚</td>
        <td>7.7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>布吉那法索</td>
        <td>13.6</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>布隆迪</td>
        <td>7.8</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>柬埔寨</td>
        <td>14.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>喀麦隆</td>
        <td>16.7</td>
        <td>混合法</td>
        <td>民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>加拿大（不包括魁北克）</td>
        <td>25</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>加那利群岛（西属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>佛得角</td>
        <td>0.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>中非共和国</td>
        <td>4.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>智利</td>
        <td>16.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>开曼群岛（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>中国（不包括香港和澳门）</td>
        <td>1 312</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>塞浦路斯</td>
        <td>0.8</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>哥伦比亚</td>
        <td>45.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>科摩罗群岛</td>
        <td>0.6</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>刚果</td>
        <td>4.1</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>库克群岛（新属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>朝鲜</td>
        <td>22.6</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>韩国</td>
        <td>8.4</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>哥斯达黎加</td>
        <td>4.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>科特迪瓦</td>
        <td>18.5</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>克罗地亚</td>
        <td>4.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>古巴</td>
        <td>11.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>丹麦（不包括格陵兰岛）</td>
        <td>5.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>吉布提</td>
        <td>0.8</td>
        <td>混合法</td>
        <td>民法/穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>多米尼克</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>苏格兰（英属）</td>
        <td>(3) 5.1</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>埃及</td>
        <td>75.4</td>
        <td>混合法</td>
        <td>穆斯林法/民法</td>
      </tr>
      <tr>
        <td>萨尔瓦多 </td>
        <td>7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿拉伯联合酋长国</td>
        <td>4.6</td>
        <td>混合法</td>
        <td>穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>厄瓜多尔</td>
        <td>13.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>厄立特里亚</td>
        <td>4.5</td>
        <td>混合法</td>
        <td>民法/习惯法/穆斯林法</td>
      </tr>
      <tr>
        <td>西班牙</td>
        <td>3.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>爱沙尼亚</td>
        <td>1.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr height="22">
        <td height="22">美国（不包括关岛、路易斯安那、马里亚那群岛、美属萨摩亚和美属维尔京群岛）</td>
        <td>(4) 294.7</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>埃塞俄比亚</td>
        <td>72.7</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>法罗群岛（丹属）</td>
        <td>(b)</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>斐济</td>
        <td>0.9</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>芬兰</td>
        <td>5.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>法国 （不包括马约特岛、新喀里多尼亚岛和法属玻利尼西亚）</td>
        <td>61</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>加蓬</td>
        <td>1.4</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>冈比亚</td>
        <td>1.6</td>
        <td>混合法</td>
        <td>穆斯林法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>格鲁吉亚</td>
        <td>4.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>南乔治亚岛与南桑威奇岛（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>加纳 </td>
        <td>22.5</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>直布罗陀（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>希腊</td>
        <td>11.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>格林纳达</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>格陵兰（丹属）</td>
        <td>0.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>瓜德罗普岛（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>关岛（美属）</td>
        <td>0.2</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>危地马拉</td>
        <td>12.9</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>根西岛（英属）</td>
        <td>(5) 0.09</td>
        <td>习惯法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>几内亚</td>
        <td>9.2</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>几内亚比绍</td>
        <td>1.6</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>赤道几内亚</td>
        <td>0.5</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>圭亚那</td>
        <td>0.8</td>
        <td>混合法</td>
        <td>普通法/民法</td>
      </tr>
      <tr>
        <td>圭亚那（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>海地</td>
        <td>8.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>夏威夷（美属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>洪都拉斯</td>
        <td>7.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>香港（中国）</td>
        <td>7</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>匈牙利</td>
        <td>10.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>印度</td>
        <td>1 109.8</td>
        <td>混合法</td>
        <td>普通法/穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>印度尼西亚</td>
        <td>223</td>
        <td>混合法</td>
        <td>民法/穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>伊朗</td>
        <td>69.2</td>
        <td>混合法</td>
        <td>穆斯林法/民法</td>
      </tr>
      <tr>
        <td>伊拉克</td>
        <td>(6) 27.5</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>爱尔兰</td>
        <td>4.2</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>北爱尔兰（英国）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>冰岛</td>
        <td>0.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>以色列</td>
        <td>7</td>
        <td>混合法</td>
        <td>民法/普通法/犹太法/穆斯林法</td>
      </tr>
      <tr>
        <td>意大利</td>
        <td>58.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>牙买加  </td>
        <td>2.7</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>日本</td>
        <td>127.6</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>泽西岛（英属）</td>
        <td>(7) 0.06</td>
        <td>习惯法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>约旦</td>
        <td>5.6</td>
        <td>混合法</td>
        <td>民法/穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>哈萨克斯坦</td>
        <td>15.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>肯尼亚</td>
        <td>35.1</td>
        <td>混合法</td>
        <td>普通法/习惯法/穆斯林法</td>
      </tr>
      <tr>
        <td>吉尔吉斯斯坦</td>
        <td>5.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>基里巴斯</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>科威特</td>
        <td>2.6</td>
        <td>混合法</td>
        <td>穆斯林法/民法/习惯法</td>
      </tr>
      <tr>
        <td>老挝</td>
        <td>5.8</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>莱索托</td>
        <td>1.8</td>
        <td>混合法</td>
        <td>普通法/民法/习惯法</td>
      </tr>
      <tr>
        <td>拉脱维亚</td>
        <td>2.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>黎巴嫩</td>
        <td>4.1</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>利比里亚</td>
        <td>3.4</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>利比亚</td>
        <td>6</td>
        <td>混合法</td>
        <td>穆斯林法/民法</td>
      </tr>
      <tr>
        <td>列支敦士登</td>
        <td>/</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>立陶宛</td>
        <td>3.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>路易斯安那（美属）</td>
        <td>(8) 4.3</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>卢森堡</td>
        <td>0.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>澳门（中国）</td>
        <td>0.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马其顿</td>
        <td>2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马达加斯加</td>
        <td>19.1</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>马德拉群岛（葡属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马来西亚 </td>
        <td>25.8</td>
        <td>混合法</td>
        <td>穆斯林法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>马拉维</td>
        <td>13.2</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>马尔代夫</td>
        <td>0.3</td>
        <td>穆斯林法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马里</td>
        <td>13.9</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>马尔维纳斯群岛/福克兰群岛（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马耳他</td>
        <td>0.4</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>马恩岛 （英属）</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马里亚纳群岛群岛（美国）</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>摩洛哥</td>
        <td>30.5</td>
        <td>混合法</td>
        <td>穆斯林法/民法</td>
      </tr>
      <tr>
        <td>马绍尔群岛</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>马提尼克岛（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>毛里求斯</td>
        <td>1.3</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>毛里塔尼亚</td>
        <td>3.2</td>
        <td>混合法</td>
        <td>穆斯林法/民法</td>
      </tr>
      <tr>
        <td>马约特岛（法属）</td>
        <td>0.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>墨西哥</td>
        <td>104.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>密克罗尼西亚</td>
        <td>0.1</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>摩尔多瓦</td>
        <td>3.8</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>摩纳哥</td>
        <td>/</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>蒙古</td>
        <td>2.6</td>
        <td>混合法</td>
        <td>习惯法/民法</td>
      </tr>
      <tr>
        <td>蒙塞瑞特（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>黑山</td>
        <td>0.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>莫桑比克</td>
        <td>20.1</td>
        <td>混合法</td>
        <td>习惯法/民法</td>
      </tr>
      <tr>
        <td>缅甸</td>
        <td>51</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>纳米比亚</td>
        <td>2.1</td>
        <td>混合法</td>
        <td>普通法/民法</td>
      </tr>
      <tr>
        <td>瑙鲁</td>
        <td>/</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>尼泊尔</td>
        <td>27.7</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>尼加拉瓜</td>
        <td>5.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>尼日尔 </td>
        <td>14.4</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>尼日利亚</td>
        <td>144.7</td>
        <td>混合法</td>
        <td>普通法/穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>纽埃（新属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>诺福克岛（澳属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>挪威 </td>
        <td>4.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>新喀里多尼亚岛（法属）</td>
        <td>0.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>新西兰</td>
        <td>4.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>阿曼</td>
        <td>2.6</td>
        <td>混合法</td>
        <td>穆斯林法/习惯法/民法</td>
      </tr>
      <tr>
        <td>乌干达</td>
        <td>29.9</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>乌兹别克斯坦 </td>
        <td>26.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>巴基斯坦 </td>
        <td>159</td>
        <td>混合法</td>
        <td>穆斯林法/普通法</td>
      </tr>
      <tr>
        <td>帕劳</td>
        <td>/</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>巴勒斯坦</td>
        <td>3.7</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>巴拿马</td>
        <td>3.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>巴布亚新几内亚</td>
        <td>6</td>
        <td>混合法</td>
        <td>习惯法/普通法</td>
      </tr>
      <tr>
        <td>巴拉圭</td>
        <td>6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>荷兰（不包括荷属安的列斯和阿鲁巴）</td>
        <td>16.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>秘鲁</td>
        <td>28.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>菲律宾</td>
        <td>84.6</td>
        <td>混合法</td>
        <td>普通法/民法</td>
      </tr>
      <tr>
        <td>比特凯恩（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>波兰</td>
        <td>38.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>波利尼西亚（法属）</td>
        <td>0.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>波多黎各岛（美属）</td>
        <td>3.9</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>葡萄牙</td>
        <td>10.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>卡塔尔</td>
        <td>0.8</td>
        <td>混合法</td>
        <td>穆斯林法/民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>魁北克（加属）</td>
        <td>(9) 7.6</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>刚果民主共和国</td>
        <td>59.3</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>多米尼加共和国</td>
        <td>9.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>捷克共和国</td>
        <td>10.2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>留尼旺岛（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>罗马尼亚</td>
        <td>21.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>英国（不包括百慕大群岛、苏格兰、根西岛、泽西岛和马恩岛）</td>
        <td>(10) 55.3</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>俄罗斯</td>
        <td>142.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>卢旺达</td>
        <td>9.2</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>圣巴特岛（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣基茨和尼维斯</td>
        <td>/</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣卢西</td>
        <td>0.2</td>
        <td>混合法</td>
        <td>民法/普通法</td>
      </tr>
      <tr>
        <td>圣赫勒拿岛（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣马力诺</td>
        <td>/</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣马丹（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣皮埃尔和米克隆岛（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣文森特和格林那丁斯</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>所罗门群岛</td>
        <td>0.5</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>萨摩亚</td>
        <td>0.2</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>美属萨摩亚</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>圣多美和普林西比</td>
        <td>0.2</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>塞内加尔</td>
        <td>11.9</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>塞尔维亚</td>
        <td>7.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>塞舌尔</td>
        <td>0.1</td>
        <td>混合法</td>
        <td>普通法/民法</td>
      </tr>
      <tr>
        <td>塞拉利昂</td>
        <td>5.6</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>新加坡</td>
        <td>4.4</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>斯洛伐克</td>
        <td>5.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>斯洛文尼亚</td>
        <td>2</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>索马里</td>
        <td>8.5</td>
        <td>混合法</td>
        <td>穆斯林法/民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>苏丹</td>
        <td>37</td>
        <td>混合法</td>
        <td>穆斯林法/普通法</td>
      </tr>
      <tr>
        <td>斯里兰卡</td>
        <td>19.8</td>
        <td>混合法</td>
        <td>民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>瑞典</td>
        <td>9</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>瑞士</td>
        <td>7.4</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>苏里南</td>
        <td>0.5</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>斯瓦茨兰</td>
        <td>1.1</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>叙利亚</td>
        <td>19.5</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>塔吉克斯坦</td>
        <td>6.7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>台湾</td>
        <td>22.8</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>坦桑尼亚</td>
        <td>39.5</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>乍得</td>
        <td>10</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>法属南部领地</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>英属南极领地</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>英属印度洋领地</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>泰国</td>
        <td>6.7</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>东帝汶</td>
        <td>1</td>
        <td>混合法</td>
        <td>民法/穆斯林法/习惯法</td>
      </tr>
      <tr>
        <td>多哥 </td>
        <td>6.3</td>
        <td>混合法</td>
        <td>民法/习惯法</td>
      </tr>
      <tr>
        <td>托克劳群岛（新属） </td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>汤加</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>特立尼达和多巴哥</td>
        <td>1.3</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>突尼斯</td>
        <td>10.1</td>
        <td>混合法</td>
        <td>民法/穆斯林法</td>
      </tr>
      <tr>
        <td>土库曼斯坦</td>
        <td>4.9</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>托克斯和凯科斯群岛（英属）</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>土耳其</td>
        <td>72.9</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>图瓦卢</td>
        <td>/</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>乌克兰</td>
        <td>46.6</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>乌拉圭 </td>
        <td>3.3</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>瓦努阿图</td>
        <td>0.2</td>
        <td>混合法</td>
        <td>民法/习惯法/普通法</td>
      </tr>
      <tr>
        <td>梵蒂冈</td>
        <td>/</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>委内瑞拉</td>
        <td>27</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>美属维尔京群岛</td>
        <td>0.1</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>英属维尔京群岛</td>
        <td>(b)</td>
        <td>普通法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>越南</td>
        <td>84.1</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>瓦利斯和富图纳群岛（法属）</td>
        <td>(b)</td>
        <td>民法</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>也门</td>
        <td>21.6</td>
        <td>混合法</td>
        <td>穆斯林法/民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>赞比亚 </td>
        <td>11.9</td>
        <td>混合法</td>
        <td>普通法/习惯法</td>
      </tr>
      <tr>
        <td>津巴布韦</td>
        <td>13.1</td>
        <td>混合法</td>
        <td>民法/普通法/习惯法</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>世界人口总数</strong></td>
        <td><strong>6 517.55</strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table>
	<p>&nbsp;</p>
	<table width="100%" border="0" cellpadding="3" cellspacing="3">
      <tr>
        <td colspan="2"><h3>信息来源:</h3></td>
      </tr>
      <tr>
        <td colspan="2">&nbsp;</td>
      </tr>
      <tr>
        <td colspan="2"><p><strong>(a)</strong> 除非有特别脚注标示，所使用的基础统计信息来源于“世界银行 KEY    DEVELOPMENT DATA &amp; STATISTICS”2006, 并由如下的信息来源加以补充：</p></td>
      </tr>
      <tr>
        <td width="5%">(1)</td>
        <td>CIA,    the World Factbook,2007 （网站）</td>
      </tr>
      <tr>
        <td>(2)</td>
        <td>32.6 -    7.6 = 25</td>
      </tr>
      <tr>
        <td>(3)</td>
        <td>General    register Office of Scotland, Census 2001 （网站）</td>
      </tr>
      <tr>
        <td>(4)</td>
        <td>299 -    4.3 = 294.7</td>
      </tr>
      <tr>
        <td>(5）</td>
        <td>同注（1）</td>
      </tr>
      <tr>
        <td>(6）</td>
        <td>同注（1）</td>
      </tr>
      <tr>
        <td>(7）</td>
        <td>同注（1）</td>
      </tr>
      <tr>
        <td>(8）</td>
        <td>U.S.    Census Bureau, Louisiana State Population （网站）</td>
      </tr>
      <tr>
        <td>(9）</td>
        <td>Gouvernement du Québec,Institut de la Statistique 2006（网站）</td>
      </tr>
      <tr>
        <td>(10)</td>
        <td>60.4    - 5.1 = 55.3</td>
      </tr>
      <tr>
        <td colspan="2"><strong>(b)</strong> 对于附属于某宗主国的政治实体，除非有特别注释，其人口统计被包括在对应的宗主国的人口统计内</td>
      </tr>
    </table>
	<!-- InstanceEndEditable --></div>

<!-- /#main-content -->
</div><!-- /#section-container -->

<?php include("http://web5.uottawa.ca/assets-templates/inc/footer-en.html"); ?>
<?php include("http://web5.uottawa.ca/assets-templates/inc/footer-contact-default-en.html"); ?>

<div id="last-updated">
Last updated: 
<?php echo date ("Y.m.d", getlastmod()) ?>

</div><!-- /#last-updated -->

</div><!-- /#main-container -->

<?php virtual("/assets/inc/beacons-en.html"); ?>

</body>
<!-- InstanceEnd --></html>
