<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en"><!-- InstanceBegin template="/Templates/cn-content-page.dwt" codeOutsideHTMLIsLocked="false" -->

<head>
<meta http-equiv="Content-Language" content="en-CA">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<!-- InstanceBeginEditable name="doctitle" -->
<title></title>
<!-- InstanceEndEditable -->

<!-- InstanceBeginEditable name="metaInformation" -->
<meta name="keywords" content="">
<meta name="description" content="">
<!-- InstanceEndEditable -->

<meta name="author" content="">
<meta name="copyright" content="&copy; University of Ottawa">

<?php include("http://web5.uottawa.ca/assets-templates/inc/head.html"); ?>

<!-- theme -->
<link type="text/css" rel="stylesheet" media="screen" href="http://web5.uottawa.ca/assets-templates/themes/08/main.css">
<!-- site-specific style sheet -->
<link type="text/css" rel="stylesheet" media="screen" href="/assets/css/section-header-cn.css">
<link type="text/css" rel="stylesheet" media="screen" href="/assets/css/main.css">

<!-- include page tools -->
<script type="text/javascript" src="http://web5.uottawa.ca/assets-templates/js/print.js"></script>
<script type="text/javascript" src="http://web5.uottawa.ca/assets-templates/js/send-to-friend.js"></script>

<!-- InstanceBeginEditable name="head" -->
<!-- page variables -->
<script type="text/javascript">
<!--
var expandNavSection = "section";
-->
</script><!-- /page variables -->
<!-- InstanceEndEditable -->
</head>

<body class="en">

<div id="main-container" class="content-page">
<!-- InstanceBeginEditable name="pageLinks" -->
	<ul id="page-links">
		<li><a id="skip-to-content" href="#main-content">Skip to content</a></li>
		<li><a id="skip-to-localnav" href="#local-nav">Skip to links</a></li>
		<li><a id="ch-lang-url" href="http://www.juriglobe.uottawa.ca/index.php" rel="alternate" lang="fr" hreflang="fr">Français</a></li>
		<li><a id="section-home" href="http://www.juriglobe.uottawa.ca/eng/index.php">Return to the home page</a></li>
	</ul>
<!-- InstanceEndEditable -->
	<!-- /#page-links -->

<?php include("http://web5.uottawa.ca/assets-templates/inc/banner-en.html"); ?>

<div id="section-container">

<!-- InstanceBeginEditable name="sectionHeader" -->
<?php virtual("/assets/inc/section-header-cn.html"); ?>
<!-- InstanceEndEditable -->

<div id="page-tools">
<div id="quickpicks">
<ul>
	<?php virtual("/assets/inc/quickpicks-en.html"); ?>
	<?php include("http://web5.uottawa.ca/assets-templates/inc/quickpicks-en.html"); ?>
</ul>
</div><!-- /#quickpicks -->
</div>
<!-- /#page-tools -->

<div id="section-details">
	<!-- InstanceBeginEditable name="Navigation" -->
	<?php virtual("/assets/inc/nav-cn.html"); ?>
	
	<!-- InstanceEndEditable -->
</div>

<div id="main-content">
<?php 
echo "<h4 align=right>";
echo "<a href=", str_replace("/chi/","/eng/",$_SERVER["PHP_SELF"]),">English</a> " ;
echo "<a href=", str_replace("/chi/","/fra/",$_SERVER["PHP_SELF"]),">Français</a> " ;
echo "<a href=", str_replace("/chi/","/esp/",$_SERVER["PHP_SELF"]),">Español</a> " ;
echo "<a href=", str_replace("/chi/","/rus/",$_SERVER["PHP_SELF"]),">Русский</a> " ;
echo "<a href=", str_replace("/chi/","/ara/",$_SERVER["PHP_SELF"]),">عربي</a> " ;
echo "</h4><hr>";
?>
	<!-- InstanceBeginEditable name="mainContent" -->
	<h2>语言和民法系</h2>
	<table cellspacing="3" cellpadding="3">
      <tr>
        <td><div align="center"><u><strong>单一制民法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿尔巴尼亚语</strong></td>
      </tr>
      <tr>
        <td>阿尔巴尼亚 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>德语</strong></td>
      </tr>
      <tr>
        <td>德国</td>
      </tr>
      <tr>
        <td>奥地利</td>
      </tr>
      <tr>
        <td>比利时</td>
      </tr>
      <tr>
        <td>列支敦士登</td>
      </tr>
      <tr>
        <td>卢森堡</td>
      </tr>
      <tr>
        <td>瑞士</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>亚美尼亚语</strong></td>
      </tr>
      <tr>
        <td>亚美尼亚 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿塞拜疆语</strong></td>
      </tr>
      <tr>
        <td>阿塞拜疆</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>白俄罗斯语</strong></td>
      </tr>
      <tr>
        <td>白俄罗斯</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>波士尼亚语</strong></td>
      </tr>
      <tr>
        <td>波斯尼亚和黑塞哥维那</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>保加利亚语</strong></td>
      </tr>
      <tr>
        <td>保加利亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>汉语</strong></td>
      </tr>
      <tr>
        <td>澳门（中国）</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>克里奥尔语</strong></td>
      </tr>
      <tr>
        <td>海地</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>克罗地亚语</strong></td>
      </tr>
      <tr>
        <td>波斯尼亚和黑塞哥维那</td>
      </tr>
      <tr>
        <td>克罗地亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>丹麦语</strong></td>
      </tr>
      <tr>
        <td>丹麦</td>
      </tr>
      <tr>
        <td>法罗群岛</td>
      </tr>
      <tr>
        <td>格陵兰</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>西班牙语</strong></td>
      </tr>
      <tr>
        <td>阿根廷</td>
      </tr>
      <tr>
        <td>玻利维亚</td>
      </tr>
      <tr>
        <td>加那利群岛（西属）</td>
      </tr>
      <tr>
        <td>智利</td>
      </tr>
      <tr>
        <td>哥伦比亚</td>
      </tr>
      <tr>
        <td>哥斯达黎加</td>
      </tr>
      <tr>
        <td>古巴</td>
      </tr>
      <tr>
        <td>萨尔瓦多 </td>
      </tr>
      <tr>
        <td>厄瓜多尔</td>
      </tr>
      <tr>
        <td>西班牙</td>
      </tr>
      <tr>
        <td>危地马拉</td>
      </tr>
      <tr>
        <td>洪都拉斯</td>
      </tr>
      <tr>
        <td>墨西哥</td>
      </tr>
      <tr>
        <td>尼加拉瓜</td>
      </tr>
      <tr>
        <td>巴拿马</td>
      </tr>
      <tr>
        <td>巴拉圭</td>
      </tr>
      <tr>
        <td>秘鲁</td>
      </tr>
      <tr>
        <td>多米尼加共和国</td>
      </tr>
      <tr>
        <td>乌拉圭</td>
      </tr>
      <tr>
        <td>委内瑞拉</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>爱沙尼亚语</strong></td>
      </tr>
      <tr>
        <td>爱沙尼亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法罗语</strong></td>
      </tr>
      <tr>
        <td>法罗群岛</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>芬兰语</strong></td>
      </tr>
      <tr>
        <td>芬兰 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法语</strong></td>
      </tr>
      <tr>
        <td>比利时</td>
      </tr>
      <tr>
        <td>贝宁</td>
      </tr>
      <tr>
        <td>中非共和国</td>
      </tr>
      <tr>
        <td>法国</td>
      </tr>
      <tr>
        <td>瓜德罗普岛（法属）</td>
      </tr>
      <tr>
        <td>圭亚那（法属）</td>
      </tr>
      <tr>
        <td>海地</td>
      </tr>
      <tr>
        <td>卢森堡</td>
      </tr>
      <tr>
        <td>马提尼克岛（法属）</td>
      </tr>
      <tr>
        <td>马约特岛（法属）</td>
      </tr>
      <tr>
        <td>摩纳哥</td>
      </tr>
      <tr>
        <td>新喀里多尼亚岛（法属）</td>
      </tr>
      <tr>
        <td>波利尼西亚（法属）</td>
      </tr>
      <tr>
        <td>留尼旺岛（法属）</td>
      </tr>
      <tr>
        <td>圣巴特岛（法属）</td>
      </tr>
      <tr>
        <td>圣马丹（法属）</td>
      </tr>
      <tr>
        <td>圣皮埃尔和米克隆岛（法属）</td>
      </tr>
      <tr>
        <td>瑞士</td>
      </tr>
      <tr>
        <td>法属南部领地</td>
      </tr>
      <tr>
        <td>瓦利斯和富图纳群岛（法属）</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>格鲁吉亚语</strong></td>
      </tr>
      <tr>
        <td>格鲁吉亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>希腊语</strong></td>
      </tr>
      <tr>
        <td>希腊</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>格陵兰语</strong></td>
      </tr>
      <tr>
        <td>格陵兰</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>瓜拉尼语</strong></td>
      </tr>
      <tr>
        <td>巴拉圭</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>匈牙利语</strong></td>
      </tr>
      <tr>
        <td>匈牙利 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>冰岛语</strong></td>
      </tr>
      <tr>
        <td>冰岛 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>意大利语</strong></td>
      </tr>
      <tr>
        <td>意大利</td>
      </tr>
      <tr>
        <td>圣马力诺</td>
      </tr>
      <tr>
        <td>瑞士</td>
      </tr>
      <tr>
        <td>梵蒂冈</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>哈萨克语</strong></td>
      </tr>
      <tr>
        <td>哈萨克斯坦</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>高绵语 </strong></td>
      </tr>
      <tr>
        <td>柬埔寨</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>吉尔吉斯语</strong></td>
      </tr>
      <tr>
        <td>吉尔吉斯斯坦</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>老挝语</strong></td>
      </tr>
      <tr>
        <td>老挝 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>拉丁语</strong></td>
      </tr>
      <tr>
        <td>梵蒂冈</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>拉脱维亚语</strong></td>
      </tr>
      <tr>
        <td>拉脱维亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>立陶宛语</strong></td>
      </tr>
      <tr>
        <td>立陶宛 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>卢森堡语</strong></td>
      </tr>
      <tr>
        <td>卢森堡 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>马其顿语</strong></td>
      </tr>
      <tr>
        <td>马其顿（前南斯拉夫马其顿共和国）</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>荷兰语</strong></td>
      </tr>
      <tr>
        <td>安的列斯群岛（荷属）</td>
      </tr>
      <tr>
        <td>阿鲁巴（荷属）</td>
      </tr>
      <tr>
        <td>比利时</td>
      </tr>
      <tr>
        <td>荷兰</td>
      </tr>
      <tr>
        <td>苏里南</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>挪威语</strong></td>
      </tr>
      <tr>
        <td>挪威 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>乌兹别克语</strong></td>
      </tr>
      <tr>
        <td>乌兹别克斯坦 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>波兰语</strong></td>
      </tr>
      <tr>
        <td>波兰 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>葡萄牙语</strong></td>
      </tr>
      <tr>
        <td>亚速尔群岛（葡属）</td>
      </tr>
      <tr>
        <td>安哥拉</td>
      </tr>
      <tr>
        <td>巴西</td>
      </tr>
      <tr>
        <td>佛得角</td>
      </tr>
      <tr>
        <td>澳门（中国）</td>
      </tr>
      <tr>
        <td>马德拉群岛（葡属）</td>
      </tr>
      <tr>
        <td>葡萄牙</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>罗马尼亚语（摩尔多瓦语）</strong></td>
      </tr>
      <tr>
        <td>摩尔多瓦</td>
      </tr>
      <tr>
        <td>罗马尼亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>俄语</strong></td>
      </tr>
      <tr>
        <td>白俄罗斯</td>
      </tr>
      <tr>
        <td>哈萨克斯坦</td>
      </tr>
      <tr>
        <td>吉尔吉斯斯坦</td>
      </tr>
      <tr>
        <td>俄罗斯</td>
      </tr>
      <tr>
        <td>塔吉克斯坦</td>
      </tr>
      <tr>
        <td>土库曼斯坦</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>桑戈语</strong></td>
      </tr>
      <tr>
        <td>中非共和国</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>塞尔维亚语</strong></td>
      </tr>
      <tr>
        <td>波斯尼亚和黑塞哥维那</td>
      </tr>
      <tr>
        <td>黑山</td>
      </tr>
      <tr>
        <td>塞尔维亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>斯洛伐克语</strong></td>
      </tr>
      <tr>
        <td>斯洛伐克</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>斯洛文尼亚语</strong></td>
      </tr>
      <tr>
        <td>斯洛文尼亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>瑞典语</strong></td>
      </tr>
      <tr>
        <td>瑞典 </td>
      </tr>
      <tr>
        <td>芬兰</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>塔吉克语（法尔西语）</strong></td>
      </tr>
      <tr>
        <td>塔吉克斯坦</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>捷克语</strong></td>
      </tr>
      <tr>
        <td>捷克共和国</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>泰语</strong></td>
      </tr>
      <tr>
        <td>泰国</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>土耳其语</strong></td>
      </tr>
      <tr>
        <td>土耳其</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>土库曼语</strong></td>
      </tr>
      <tr>
        <td>土库曼斯坦</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>乌克兰语</strong></td>
      </tr>
      <tr>
        <td>乌克兰</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>越南语</strong></td>
      </tr>
      <tr>
        <td>越南</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>民法和普通法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>南非荷兰语</strong></td>
      </tr>
      <tr>
        <td>南非 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>英语</strong></td>
      </tr>
      <tr>
        <td>南非</td>
      </tr>
      <tr>
        <td>博茨瓦纳</td>
      </tr>
      <tr>
        <td>苏格兰（英属）</td>
      </tr>
      <tr>
        <td>圭亚那</td>
      </tr>
      <tr>
        <td>路易斯安那（美属）</td>
      </tr>
      <tr>
        <td>马耳他</td>
      </tr>
      <tr>
        <td>毛里求斯</td>
      </tr>
      <tr>
        <td>纳米比亚</td>
      </tr>
      <tr>
        <td>菲律宾</td>
      </tr>
      <tr>
        <td>波多黎各岛（美属）</td>
      </tr>
      <tr>
        <td>魁北克（加属）</td>
      </tr>
      <tr>
        <td>圣卢西</td>
      </tr>
      <tr>
        <td>塞舌尔</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>克里奥尔语</strong></td>
      </tr>
      <tr>
        <td>塞舌尔</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>西班牙语</strong></td>
      </tr>
      <tr>
        <td>波多黎各岛（美属）</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法语</strong></td>
      </tr>
      <tr>
        <td>毛里求斯</td>
      </tr>
      <tr>
        <td>魁北克（加属）</td>
      </tr>
      <tr>
        <td>塞舌尔</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>希腊语</strong></td>
      </tr>
      <tr>
        <td>塞浦路斯</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>马耳他语</strong></td>
      </tr>
      <tr>
        <td>马耳他 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>他加禄语</strong></td>
      </tr>
      <tr>
        <td>菲律宾</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>土耳其语</strong></td>
      </tr>
      <tr>
        <td>塞浦路斯</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>民法和习惯法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿姆哈拉语</strong></td>
      </tr>
      <tr>
        <td>埃塞俄比亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>英语</strong></td>
      </tr>
      <tr>
        <td>卢旺达</td>
      </tr>
      <tr>
        <td>斯瓦茨兰</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿拉伯语</strong></td>
      </tr>
      <tr>
        <td>乍得</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>汉语</strong></td>
      </tr>
      <tr>
        <td>中国（不包括香港和澳门）</td>
      </tr>
      <tr>
        <td>台湾</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>朝鲜语</strong></td>
      </tr>
      <tr>
        <td>韩国</td>
      </tr>
      <tr>
        <td>朝鲜 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>西班牙语</strong></td>
      </tr>
      <tr>
        <td>赤道几内亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法语</strong></td>
      </tr>
      <tr>
        <td>布吉那法索</td>
      </tr>
      <tr>
        <td>布隆迪</td>
      </tr>
      <tr>
        <td>刚果</td>
      </tr>
      <tr>
        <td>科特迪瓦</td>
      </tr>
      <tr>
        <td>加蓬</td>
      </tr>
      <tr>
        <td>几内亚</td>
      </tr>
      <tr>
        <td>赤道几内亚</td>
      </tr>
      <tr>
        <td>马达加斯加</td>
      </tr>
      <tr>
        <td>马里</td>
      </tr>
      <tr>
        <td>尼日尔 </td>
      </tr>
      <tr>
        <td>刚果民主共和国</td>
      </tr>
      <tr>
        <td>卢旺达</td>
      </tr>
      <tr>
        <td>塞内加尔</td>
      </tr>
      <tr>
        <td>乍得</td>
      </tr>
      <tr>
        <td>多哥</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>日语</strong></td>
      </tr>
      <tr>
        <td>日本</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>卢旺达语</strong></td>
      </tr>
      <tr>
        <td>卢旺达 </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>布隆迪语</strong></td>
      </tr>
      <tr>
        <td>布隆迪</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>马达加斯加语</strong></td>
      </tr>
      <tr>
        <td>马达加斯加</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>蒙语</strong></td>
      </tr>
      <tr>
        <td>蒙古</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>葡萄牙语</strong></td>
      </tr>
      <tr>
        <td>几内亚比绍</td>
      </tr>
      <tr>
        <td>莫桑比克</td>
      </tr>
      <tr>
        <td>圣多美和普林西比</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>斯瓦茨语</strong></td>
      </tr>
      <tr>
        <td>斯瓦茨兰</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>民法和穆斯林法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿拉伯语</strong></td>
      </tr>
      <tr>
        <td>阿尔及利亚</td>
      </tr>
      <tr>
        <td>科摩罗群岛</td>
      </tr>
      <tr>
        <td>埃及</td>
      </tr>
      <tr>
        <td>伊拉克</td>
      </tr>
      <tr>
        <td>黎巴嫩</td>
      </tr>
      <tr>
        <td>利比亚</td>
      </tr>
      <tr>
        <td>摩洛哥</td>
      </tr>
      <tr>
        <td>毛里塔尼亚</td>
      </tr>
      <tr>
        <td>巴勒斯坦</td>
      </tr>
      <tr>
        <td>叙利亚</td>
      </tr>
      <tr>
        <td>突尼斯</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法语</strong></td>
      </tr>
      <tr>
        <td>科摩罗群岛</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>库尔德语</strong></td>
      </tr>
      <tr>
        <td>伊拉克</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>波斯语（法尔西语）</strong></td>
      </tr>
      <tr>
        <td>伊朗</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>斯克摩语</strong></td>
      </tr>
      <tr>
        <td>科摩罗群岛</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>民法、穆斯林法和习惯法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿拉伯语</strong></td>
      </tr>
      <tr>
        <td>吉布提</td>
      </tr>
      <tr>
        <td>厄立特里亚</td>
      </tr>
      <tr>
        <td>约旦</td>
      </tr>
      <tr>
        <td>科威特</td>
      </tr>
      <tr>
        <td>阿曼</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>印尼语</strong></td>
      </tr>
      <tr>
        <td>印度尼西亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法语</strong></td>
      </tr>
      <tr>
        <td>吉布提</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>葡萄牙语</strong></td>
      </tr>
      <tr>
        <td>东帝汶</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>德顿语</strong></td>
      </tr>
      <tr>
        <td>东帝汶</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>提格雷尼亚语</strong></td>
      </tr>
      <tr>
        <td>厄立特里亚</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>民法、普通法和习惯法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>英语</strong></td>
      </tr>
      <tr>
        <td>喀麦隆</td>
      </tr>
      <tr>
        <td>莱索托</td>
      </tr>
      <tr>
        <td>瓦努阿图</td>
      </tr>
      <tr>
        <td>津巴布韦</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>比斯拉马语</strong></td>
      </tr>
      <tr>
        <td>瓦努阿图</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>僧伽罗语</strong></td>
      </tr>
      <tr>
        <td>斯里兰卡</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>法语</strong></td>
      </tr>
      <tr>
        <td>喀麦隆</td>
      </tr>
      <tr>
        <td>瓦努阿图</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>塞苏陀语</strong></td>
      </tr>
      <tr>
        <td>莱索托</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>泰米尔语</strong></td>
      </tr>
      <tr>
        <td>斯里兰卡</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>普通法、穆斯林法、民法和习惯法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿拉伯语</strong></td>
      </tr>
      <tr>
        <td>巴林 </td>
      </tr>
      <tr>
        <td>卡塔尔</td>
      </tr>
      <tr>
        <td>也门</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>索马里语</strong></td>
      </tr>
      <tr>
        <td>索马里</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><div align="center"><u><strong>民法、普通法、犹太法和穆斯林法混合法系：</strong></u></div></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>阿拉伯语</strong></td>
      </tr>
      <tr>
        <td>以色列</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td><strong>希伯来语</strong></td>
      </tr>
      <tr>
        <td>以色列</td>
      </tr>
    </table>
	<!-- InstanceEndEditable -->
</div>

<!-- /#main-content -->
</div><!-- /#section-container -->

<?php include("http://web5.uottawa.ca/assets-templates/inc/footer-en.html"); ?>
<?php include("http://web5.uottawa.ca/assets-templates/inc/footer-contact-default-en.html"); ?>

<div id="last-updated">
Last updated: 
<?php echo date ("Y.m.d", getlastmod()) ?>

</div><!-- /#last-updated -->

</div><!-- /#main-container -->

<?php virtual("/assets/inc/beacons-en.html"); ?>

</body>
<!-- InstanceEnd --></html>
